import type {
  DemoAiEmployee,
  DemoApproval,
  DemoAuditLog,
  DemoCompany,
  DemoIncident,
  DemoLaunchGate,
  DemoMarketplaceTemplate,
  DemoPricingPlan,
  DemoUser,
  DemoWorkflow,
  DemoWorkspace,
} from "@/lib/demo-data/types";

export const demoCompany: DemoCompany = {
  id: "org_novara_group",
  name: "Novara Group",
  industry: "B2B SaaS & Professional Services",
  region: "EU",
  headquarters: "Berlin, Germany",
  employeeCount: 420,
  plan: "Smart",
  workspaceCount: 4,
  primaryWorkspace: "Revenue Operations",
  status: "Enterprise Pilot",
  dataResidency: "EU-Central",
  complianceProfile: [
    "GDPR-ready demo posture",
    "SOC 2 evidence in progress",
    "Enterprise audit logs enabled",
  ],
};

export const demoWorkspaces: DemoWorkspace[] = [
  {
    id: "ws_revops",
    name: "Revenue Operations",
    owner: "Maya Schneider",
    plan: "Smart",
    activeAiEmployees: 7,
    activeWorkflows: 12,
    riskStatus: "Low",
    monthlyAiCost: 1840,
    primaryOutcome: "Improve lead response speed and pipeline hygiene",
  },
  {
    id: "ws_customer_success",
    name: "Customer Success",
    owner: "Daniel Weber",
    plan: "Smart",
    activeAiEmployees: 5,
    activeWorkflows: 9,
    riskStatus: "Medium",
    monthlyAiCost: 1260,
    primaryOutcome: "Detect churn risk earlier and improve onboarding follow-through",
  },
  {
    id: "ws_finance_ops",
    name: "Finance Operations",
    owner: "Elena Rossi",
    plan: "Pro",
    activeAiEmployees: 3,
    activeWorkflows: 6,
    riskStatus: "Medium",
    monthlyAiCost: 740,
    primaryOutcome: "Reduce invoice exception handling time",
  },
];

export const demoUsers: DemoUser[] = [
  {
    id: "user_maya",
    name: "Maya Schneider",
    email: "maya.schneider@novaragroup.example",
    role: "Workspace Owner",
    team: "Revenue Operations",
    permissions: ["Manage AI Employees", "Approve Workflows", "View Cost"],
    locale: "en-DE",
    direction: "ltr",
  },
  {
    id: "user_jonas",
    name: "Jonas Mueller",
    email: "jonas.mueller@novaragroup.example",
    role: "Security Admin",
    team: "IT & Security",
    permissions: ["Manage Policies", "Review Permissions", "View Audit Logs"],
    locale: "en-DE",
    direction: "ltr",
  },
  {
    id: "user_sara",
    name: "Sara Ahmadi",
    email: "sara.ahmadi@novaragroup.example",
    role: "Customer Success Manager",
    team: "Customer Success",
    permissions: ["View Accounts", "Run Playbooks", "Request AI Employee Changes"],
    locale: "fa-IR",
    direction: "rtl",
  },
];

export const demoAiEmployees: DemoAiEmployee[] = [
  {
    id: "ae_revenue_followup",
    name: "Revenue Follow-up Analyst",
    workspace: "Revenue Operations",
    owner: "Maya Schneider",
    status: "Active",
    planRequired: "Pro",
    health: 92,
    riskLevel: "Low",
    monthlyCost: 420,
    version: "v1.8.2",
    primaryOutcome: "Reduce lead follow-up delay",
    outcomeMetric: "Median follow-up time reduced from 18h to 3.4h",
    tools: ["CRM", "Email", "Calendar", "Lead Enrichment"],
    knowledgeSources: ["Sales playbook", "ICP rules", "Objection library"],
    memoryScope: "Workspace-level sales context",
    lastReviewed: "2026-06-14",
    nextReviewDue: "2026-07-14",
  },
  {
    id: "ae_support_triage",
    name: "Support Triage Coordinator",
    workspace: "Customer Success",
    owner: "Daniel Weber",
    status: "Needs Review",
    planRequired: "Pro",
    health: 78,
    riskLevel: "Medium",
    monthlyCost: 360,
    version: "v1.3.0",
    primaryOutcome: "Classify and route support escalations faster",
    outcomeMetric: "Escalation response SLA improved by 31%",
    tools: ["Helpdesk", "Slack", "Customer Health", "Knowledge Base"],
    knowledgeSources: ["Support policies", "Escalation matrix", "Product FAQ"],
    memoryScope: "Customer-support interaction summary",
    lastReviewed: "2026-06-06",
    nextReviewDue: "2026-06-21",
  },
  {
    id: "ae_policy_guardian",
    name: "AI Policy Guardian",
    workspace: "IT & Security",
    owner: "Jonas Mueller",
    status: "Active",
    planRequired: "Smart",
    health: 95,
    riskLevel: "Low",
    monthlyCost: 300,
    version: "v1.5.7",
    primaryOutcome: "Review risky AI Employee changes before launch",
    outcomeMetric: "18 high-risk changes blocked or routed this quarter",
    tools: ["Policy Engine", "Audit Logs", "Approval Queue"],
    knowledgeSources: ["Security policy", "Data residency rules", "Marketplace policy"],
    memoryScope: "Policy review history only",
    lastReviewed: "2026-06-17",
    nextReviewDue: "2026-07-17",
  },
];

export const demoWorkflows: DemoWorkflow[] = [
  {
    id: "wf_lead_response",
    name: "Qualified Lead Response Workflow",
    workspace: "Revenue Operations",
    status: "Active",
    owner: "Maya Schneider",
    assignedAiEmployees: ["Revenue Follow-up Analyst"],
    trigger: "New qualified lead enters CRM",
    steps: 6,
    humanApprovalRequired: false,
    riskLevel: "Low",
    lastRun: "2026-06-19T09:12:00+02:00",
    successRate: 94,
    monthlyRuns: 1280,
    avgRuntime: "2m 14s",
    businessOutcome: "Faster lead response and cleaner pipeline data",
  },
  {
    id: "wf_invoice_exception",
    name: "Invoice Exception Triage Workflow",
    workspace: "Finance Operations",
    status: "Pending Approval",
    owner: "Elena Rossi",
    assignedAiEmployees: ["Invoice Exception Reviewer", "AI Policy Guardian"],
    trigger: "Invoice flagged with payment mismatch",
    steps: 8,
    humanApprovalRequired: true,
    riskLevel: "Medium",
    lastRun: "Simulation only",
    successRate: 87,
    monthlyRuns: 0,
    avgRuntime: "Projected 4m 40s",
    businessOutcome: "Reduce manual finance triage without auto-approving payment changes",
  },
];

export const demoMarketplaceTemplates: DemoMarketplaceTemplate[] = [
  {
    id: "tpl_revenue_followup_starter",
    name: "Revenue Follow-up Starter Kit",
    category: "Revenue Operations",
    type: "AI Employee Template",
    creator: "Ariyo Verified",
    trustLabel: "Certified",
    rating: 4.8,
    reviews: 126,
    installs: 1840,
    planRequired: "Pro",
    regionCompatibility: ["EU", "US"],
    permissionRisk: "Low",
    pricing: "Included in Pro and Smart",
    shortDescription: "Deploy a governed AI Employee for lead follow-up and CRM hygiene.",
    outcomes: ["Faster lead response", "Cleaner CRM updates", "Consistent follow-up quality"],
  },
  {
    id: "tpl_customer_health_risk",
    name: "Customer Health Risk Monitor",
    category: "Customer Success",
    type: "Agent Team Template",
    creator: "Ariyo Verified",
    trustLabel: "Certified",
    rating: 4.9,
    reviews: 210,
    installs: 2310,
    planRequired: "Smart",
    regionCompatibility: ["EU", "US", "UK"],
    permissionRisk: "Medium",
    pricing: "Included in Smart",
    shortDescription: "Detect account health declines and trigger governed success playbooks.",
    outcomes: ["Earlier churn detection", "Better renewal preparation", "Consistent playbooks"],
  },
];

export const demoApprovals: DemoApproval[] = [
  {
    id: "appr_1001",
    title: "Approve Invoice Exception Triage Workflow",
    requester: "Elena Rossi",
    approver: "Jonas Mueller",
    riskLevel: "Medium",
    status: "Pending",
    requestedAt: "2026-06-18T14:30:00+02:00",
    dueAt: "2026-06-20T17:00:00+02:00",
    reason: "Workflow requires ERP read access and finance exception classification.",
    decisionOptions: ["Approve", "Approve with limits", "Request changes", "Reject"],
  },
];

export const demoIncidents: DemoIncident[] = [
  {
    id: "inc_2401",
    title: "Support Triage Coordinator routed 14 tickets to delayed queue",
    severity: "Medium",
    status: "Investigating",
    owner: "Daniel Weber",
    affectedSurface: "Customer Success",
    affectedAiEmployee: "Support Triage Coordinator",
    detectedAt: "2026-06-19T07:55:00+02:00",
    customerImpact: "Delayed escalation response for 3 accounts",
    nextAction: "Review routing rule and re-run simulation",
    auditAvailable: true,
  },
];

export const demoAuditLogs: DemoAuditLog[] = [
  {
    id: "log_9001",
    timestamp: "2026-06-19T09:14:00+02:00",
    actor: "Maya Schneider",
    action: "Updated monthly cost cap",
    object: "Revenue Follow-up Analyst",
    riskLevel: "Low",
    result: "Applied",
    evidence: "Change request CR-1842",
  },
];

export const demoPricingPlans: DemoPricingPlan[] = [
  {
    name: "Basic",
    audience: "Small teams starting with governed AI work",
    priceLabel: "Starting package",
    aiEmployees: "Up to 3",
    workflows: "Basic workflows",
    marketplace: "Starter templates",
    governance: "Basic approvals",
    support: "Standard support",
    bestFor: "Low-risk internal productivity",
  },
  {
    name: "Pro",
    audience: "Operational teams deploying AI Employees across workflows",
    priceLabel: "Team package",
    aiEmployees: "Up to 15",
    workflows: "Advanced workflow builder",
    marketplace: "Pro templates",
    governance: "Role-based approvals",
    support: "Priority support",
    bestFor: "Revenue, Support, and Finance operations",
  },
  {
    name: "Smart",
    audience: "Enterprise-ready teams needing governance and intelligence",
    priceLabel: "Advanced operating package",
    aiEmployees: "Unlimited governed AI Employees",
    workflows: "Simulation, versioning, and advanced controls",
    marketplace: "Certified templates and private catalog",
    governance: "Policy engine, audit logs, data residency controls",
    support: "Premium success support",
    bestFor: "Accountable AI Employee operations at scale",
  },
  {
    name: "Enterprise",
    audience: "Large organizations with procurement and compliance requirements",
    priceLabel: "Contact sales",
    aiEmployees: "Custom operating limits",
    workflows: "Enterprise implementation support",
    marketplace: "Private catalog and vendor controls",
    governance: "SSO/SCIM preview, advanced policy, evidence center",
    support: "Dedicated success and implementation",
    bestFor: "Cross-functional AI operating systems",
  },
];

export const demoLaunchGates: DemoLaunchGate[] = [
  { name: "Product MVP", score: 88, status: "Ready" },
  { name: "Design System", score: 82, status: "Ready with constraints" },
  { name: "Marketplace Alpha", score: 74, status: "Needs Review" },
  { name: "Trust & Compliance", score: 79, status: "Needs evidence updates" },
];
